java.lang.RuntimeException: __the_message__!
  at com.google.j2cl.junit.integration.stacktrace.data.ExceptionWithCauseStacktraceTest.test(ExceptionWithCauseStacktraceTest.java:29)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException: root cause
On two lines
  at com.google.j2cl.junit.integration.stacktrace.data.ExceptionWithCauseStacktraceTest.method(ExceptionWithCauseStacktraceTest.java:34)
  at com.google.j2cl.junit.integration.stacktrace.data.ExceptionWithCauseStacktraceTest.test(ExceptionWithCauseStacktraceTest.java:27)
  ... 27 more
Caused by: java.lang.NullPointerException: root cause
On two lines
  ... 29 more